version: '3.8'

services:
  
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: root
    volumes:
      - ./relacoes-prates-ddl.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./relacoes-prates-dml.sql:/docker-entrypoint-initdb.d/20-init.sql
    restart: always
  
  frontend:
    build: ./frontend
    container_name: client
    ports:
      - "3000:3000"
  
  backend:
    build: ./backend
    container_name: api
    ports:
      - "5000:5000"


